import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Prevalence of cocaine in the EU population",
  "subtitle": "Share of cocaine use in the European Union in 2024 among the European population aged 15 to 64 (or most recent data available)",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.015,true,Survey year 2022,,,,,,,,\nBelgium,BE,0.014,true,Survey year 2018,,,,,,,,\nBulgaria,BG,0.006,true,Survey year 2020,,,,,,,,\nCyprus,CY,0.007,true,Survey year 2022,,,,,,,,\nCzechia,CZ,0.004,true,Survey year 2023,,,,,,,,\nGermany,DE,0.016,true,Survey year 2021,,,,,,,,\nDenmark,DK,0.021,true,Survey year 2023,,,,,,,,\nGreece,EL,0.004,true,Survey year 2015,,,,,,,,\nEstonia,EE,0.021,true,Survey year 2022,,,,,,,,\nSpain,ES,0.025,FALSE,,,,,,,,,\nFinland,FI,0.016,true,Survey year 2022,,,,,,,,\nFrance,FR,0.027,true,Survey year 2022,,,,,,,,\nCroatia,HR,0.018,true,Survey year 2019,,,,,,,,\nHungary,HU,0.003,true,Survey year 2019,,,,,,,,\nIreland,IE,0.023,true,Survey year 2019,,,,,,,,\nItaly,IT,0.014,true,Survey year 2022,,,,,,,,\nLithuania,LT,0.006,true,Survey year 2021,,,,,,,,\nLuxembourg,LU,0.005,true,Survey year 2019,,,,,,,,\nLatvia,LV,0.013,true,Survey year 2020,,,,,,,,\nNetherlands,NL,0.027,true,Survey year 2023,,,,,,,,\nPoland,PL,0.004,FALSE,,,,,,,,,\nPortugal,PT,0.002,true,Survey year 2022,,,,,,,,\nRomania,RO,0.005,true,Survey year 2019,,,,,,,,\nSweden,SE,0.013,true,Survey year 2021,,,,,,,,\nSlovenia,SI,0.009,true,Survey year 2023,,,,,,,,\nSlovakia,SK,0.005,true,Survey year 2023,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.015,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.014,
      "extraInfo": true,
      "text_content": "Survey year 2018",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.006,
      "extraInfo": true,
      "text_content": "Survey year 2020",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.007,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.004,
      "extraInfo": true,
      "text_content": "Survey year 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.016,
      "extraInfo": true,
      "text_content": "Survey year 2021",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.021,
      "extraInfo": true,
      "text_content": "Survey year 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.004,
      "extraInfo": true,
      "text_content": "Survey year 2015",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.021,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.025,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.016,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.027,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.018,
      "extraInfo": true,
      "text_content": "Survey year 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.003,
      "extraInfo": true,
      "text_content": "Survey year 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.023,
      "extraInfo": true,
      "text_content": "Survey year 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.014,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.006,
      "extraInfo": true,
      "text_content": "Survey year 2021",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.005,
      "extraInfo": true,
      "text_content": "Survey year 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.013,
      "extraInfo": true,
      "text_content": "Survey year 2020",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.027,
      "extraInfo": true,
      "text_content": "Survey year 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.004,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.002,
      "extraInfo": true,
      "text_content": "Survey year 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.005,
      "extraInfo": true,
      "text_content": "Survey year 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.013,
      "extraInfo": true,
      "text_content": "Survey year 2021",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.009,
      "extraInfo": true,
      "text_content": "Survey year 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.005,
      "extraInfo": true,
      "text_content": "Survey year 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "blue",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "EMCDDA",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "No data available for Malta",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.euda.europa.eu/publications/european-drug-report/2025/cocaine_en",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of adults",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Prevalence of cocaine in the EU population",
    "subtitle": "Share of cocaine use in the European Union in 2024 among the European population aged 15 to 64 (or most recent data available)",
    "textNoteDescription": "Note",
    "textNote": "No data available for Malta",
    "textSourceDescription": "Source",
    "textSource": "EMCDDA",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "Survey year 2022",
    "extraInfo_BE": "Survey year 2018",
    "extraInfo_BG": "Survey year 2020",
    "extraInfo_CY": "Survey year 2022",
    "extraInfo_CZ": "Survey year 2023",
    "extraInfo_DE": "Survey year 2021",
    "extraInfo_DK": "Survey year 2023",
    "extraInfo_EL": "Survey year 2015",
    "extraInfo_EE": "Survey year 2022",
    "extraInfo_FI": "Survey year 2022",
    "extraInfo_FR": "Survey year 2022",
    "extraInfo_HR": "Survey year 2019",
    "extraInfo_HU": "Survey year 2019",
    "extraInfo_IE": "Survey year 2019",
    "extraInfo_IT": "Survey year 2022",
    "extraInfo_LT": "Survey year 2021",
    "extraInfo_LU": "Survey year 2019",
    "extraInfo_LV": "Survey year 2020",
    "extraInfo_NL": "Survey year 2023",
    "extraInfo_PT": "Survey year 2022",
    "extraInfo_RO": "Survey year 2019",
    "extraInfo_SE": "Survey year 2021",
    "extraInfo_SI": "Survey year 2023",
    "extraInfo_SK": "Survey year 2023"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Survey year 2022",
  "extraInfo_BE": "Survey year 2018",
  "extraInfo_BG": "Survey year 2020",
  "extraInfo_CY": "Survey year 2022",
  "extraInfo_CZ": "Survey year 2023",
  "extraInfo_DE": "Survey year 2021",
  "extraInfo_DK": "Survey year 2023",
  "extraInfo_EL": "Survey year 2015",
  "extraInfo_EE": "Survey year 2022",
  "extraInfo_FI": "Survey year 2022",
  "extraInfo_FR": "Survey year 2022",
  "extraInfo_HR": "Survey year 2019",
  "extraInfo_HU": "Survey year 2019",
  "extraInfo_IE": "Survey year 2019",
  "extraInfo_IT": "Survey year 2022",
  "extraInfo_LT": "Survey year 2021",
  "extraInfo_LU": "Survey year 2019",
  "extraInfo_LV": "Survey year 2020",
  "extraInfo_NL": "Survey year 2023",
  "extraInfo_PT": "Survey year 2022",
  "extraInfo_RO": "Survey year 2019",
  "extraInfo_SE": "Survey year 2021",
  "extraInfo_SI": "Survey year 2023",
  "extraInfo_SK": "Survey year 2023"
});